export default {
    appName: 'AI Pal',
    appleLogin: 'Continue with Apple',
    googleLogin: 'Continue with Google',
    emailSignUp: 'Sign Up with Email',
    login: 'Login',
    createAccount: 'Create your Account',
    welcomeBack: 'Welcome Back',
    createAccoutButton: 'Create Account',
    loginButton: 'Login',

    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',

    email: 'email',
    password: 'password',
    delete: 'Delete',
    cancel: 'Cancel',
    rename: 'Rename',
    save: 'Save',
    logout: 'Logout',
    imageNotSupportedModel: 'Image generation is not supported for this model',
    deleteChatHistory: 'Delete Chat History',
    deleteChatHistoryConfirm: 'Are you sure you want to delete chat history?',
    deleteChatHistorySuccess: 'Chat history deleted successfully',
    circleSearchResponse: 'Circle to Search Response',
    copiedToClipboard: 'Copied to clipboard',
    deleteChatSuccess: 'Chat deleted successfully',
} as const;
